language: java

before_install:
  - chmod +x mvnw
  
install:
    - mvn -N io.takari:maven:wrapper
    - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jdk:
    - oraclejdk8

script:
    - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 415fa45f-a930-4e63-9ee8-acc3c3e9ed5f
